### ISSUE TITLE
Center all content in mobile view

### ISSUE THREAD

**Issue by Zohair-coder** [caglarturali/caglarturali.github.io#271]
Thanks a lot for making this portfolio open-source.

When viewing the site on mobile, the page isn't perfectly centered. The content visibly leans more to the left than to the right. The navbar is also not covering the entire top part of the screen.

**Comment by Zohair-coder** [comment]
Fixed the issue in pull request #272

**Comment by caglarturali** [comment]
Sorry for the late response, but I'm no longer maintaining this project. Feel free to use it in whatever way you like. :)
